version: "1"
services:
  backend:
    container_name: obligatorio--backend
    build: ./
    image: obligatorio--backend
    environment:
      # Server settings
      PORT: 80
      SERVICE_NAME: "Backend"
      # Database settings
      RDS_PORT: 3306
      RDS_HOSTNAME: mysql
      RDS_USERNAME: root
      RDS_PASSWORD: Password1
      RDS_DB_NAME: ihc_db
      # Node mode
      NODE_ENV: development
      # JWT settings
      JWT_SECRET_KEY: t5&iPrL6$_r9
      JWT_SECRET_KEY_INVITE: tru*3UdrO+ls
    volumes:
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./.env.example:/opt/app/.env.example
      - ./knexfile.js:/opt/app/knexfile.js
      - ./src/persistence/knex/migrations:/app/migrations  # Ruta local a tus migraciones
    command: sh -c "sleep 10 && knex migrate:latest && npm run start"
    restart: on-failure
    ports:
      - "8000:80"
    networks:
      - obligatorio
    depends_on:
      - mysql
  mysql:
    container_name: obligatorio--mysql
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_VERSION: 8.0
      MYSQL_PORT: 3306
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Password1
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: ihc_db
      MYSQL_TIMEZONE: "+00:00"
    volumes:
      - obligatorio--mysql-data:/data/db
    ports:
      - "3306:3306"
    networks:
      - obligatorio
volumes:
  obligatorio--mysql-data:
networks:
  obligatorio:
    driver: bridge
